// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	model "learngo/restapiserver/pkg/movies/models"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateMovie provides a mock function with given fields: movie
func (_m *Service) CreateMovie(movie model.MovieTable) error {
	ret := _m.Called(movie)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.MovieTable) error); ok {
		r0 = rf(movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMovie provides a mock function with given fields: id
func (_m *Service) DeleteMovie(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListMovies provides a mock function with given fields: page, pagesize
func (_m *Service) ListMovies(page int, pagesize int) (error, []model.MovieTable) {
	ret := _m.Called(page, pagesize)

	var r0 error
	var r1 []model.MovieTable
	if rf, ok := ret.Get(0).(func(int, int) (error, []model.MovieTable)); ok {
		return rf(page, pagesize)
	}
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(page, pagesize)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(int, int) []model.MovieTable); ok {
		r1 = rf(page, pagesize)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]model.MovieTable)
		}
	}

	return r0, r1
}

// ListOneMovie provides a mock function with given fields: id
func (_m *Service) ListOneMovie(id int) (error, model.MovieTable) {
	ret := _m.Called(id)

	var r0 error
	var r1 model.MovieTable
	if rf, ok := ret.Get(0).(func(int) (error, model.MovieTable)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(int) model.MovieTable); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(model.MovieTable)
	}

	return r0, r1
}

// UpdateMovie provides a mock function with given fields: id, updatedMovie
func (_m *Service) UpdateMovie(id int, updatedMovie model.MovieTable) error {
	ret := _m.Called(id, updatedMovie)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, model.MovieTable) error); ok {
		r0 = rf(id, updatedMovie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
